version: '3'
services:
  web:
    image: "tanish/chat"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL = env("DATABASE_URL")
      - REDIS_URL = env("REDIS_URL")
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: NDZEfr9t4MHh
      POSTGRES_DB: verceldb

volumes:
  postgres_data:
  redis_data:
  