version: '3'
services:
  web:
    build: .
    image: "tanish/chat"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis
      - db

  redis:
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: NDZEfr9t4MHh
      POSTGRES_DB: verceldb

volumes:
  postgres_data:
  redis_data:
